name: Reportes en Festify游냍 
description: Reporta un error en la app FESTIFY.
labels: ["estado: necesita revisi칩n"]
body:
  - type: markdown
    attributes:
      value: |
        Sistema de reportes de festify, se claro.
  - type: textarea
    attributes:
      label: Comportamiento Actual
      description: Una descripci칩n concisa de lo que est치s experimentando.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento Esperado
      description: Una descripci칩n concisa de lo que esperabas que sucediera.
    validations:
      required: true  
  - type: textarea
    attributes:
      label: Pasos para Reproducir
      description: |
        Por favor, s칠 lo m치s detallado posible aqu칤 para que podamos ayudar a diagnosticar el problema. Los problemas no pueden ser aceptados si son demasiado vagos. Por ejemplo, 'el proyecto no se compila' no ser칤a reproducible.
      placeholder: |
        1. Crear nueva p치gina
        2. Agregar widget de contenedor
        3. Establecer ancho = 123
        4. Hacer clic en Ejecutar
        5. Observar que el proyecto no se compila
    validations:
      required: false
  - type: textarea
    attributes:
      label: Documentaci칩n Visual
      description: |
        Im치genes y/o un breve video que muestren los pasos para reproducir el problema que est치s reportando.
       
        Agregar im치genes y fragmentos de video ayudar치 a acelerar la investigaci칩n y nos permitir치 resolver problemas m치s r치pidamente.

        Consejo: Puedes adjuntar im치genes o archivos de registro haciendo clic en esta 치rea para resaltarlo y luego arrastrando archivos.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Informaci칩n Adicional
      description: |
        Cualquier captura de pantalla adicional, grabaciones, enlaces, referencias o cualquier otra cosa que nos brinde m치s contexto sobre el problema que est치s encontrando.

        Consejo: Puedes adjuntar im치genes o archivos de registro haciendo clic en esta 치rea para resaltarlo y luego arrastrando archivos.
    validations:
      required: false
